APP_NAME = "Manga Studio AI"
APP_VERSION = "1.0.0"
HOST = "127.0.0.1"
PORT = 5000
DEBUG = False

SUPPORTED_IMAGE_FORMATS = ['.jpg', '.jpeg', '.png', '.webp']
SUPPORTED_AUDIO_FORMATS = ['.mp3', '.wav', '.m4a']

DEFAULT_FPS = 60
DEFAULT_RESOLUTION = "1920x1080"
DEFAULT_VIDEO_CODEC = "libx264"
DEFAULT_AUDIO_CODEC = "aac"
DEFAULT_VIDEO_BITRATE = "8M"
DEFAULT_AUDIO_BITRATE = "192k"

EFFECT_SPEEDS = {"slow": 8, "normal": 5, "fast": 3}
TRANSITION_DURATIONS = [0.3, 0.5, 1.0]